# Generated by Django 5.0.6 on 2024-06-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_totp_account_totp__otp_totp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totp',
            name='purpose',
            field=models.CharField(choices=[('PasswordReset', 'Password Reset'), ('EmailVerification', 'Email Verification'), ('PhoneVerification', 'Phone Verification'), ('AccountVerification', 'Account Verification')], max_length=100),
        ),
    ]
