# Generated by Django 5.0.6 on 2024-06-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_totp_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='totp',
            name='expiration_time',
            field=models.DateTimeField(default='2024-05-16 07:07:07'),
            preserve_default=False,
        ),
    ]
